####################################
#DB Connection
####################################
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_mgt
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/real_estate_db
spring.datasource.username=postgres
spring.datasource.password=win

app.config.get_public_docs_upload_location=/Users/johnassiamah/elis/documents/web_docs/
app.config.case_upload_location=/Users/johnassiamah/elis/documents/case_docs/
app.config.public_docs_upload_location=/Users/johnassiamah/elis/documents/web_docs/
app.config.softfile_location=/Users/johnassiamah/elis/softfiles/
app.config.sample_sign_location=/Users/johnassiamah/elis/softfiles/
app.config.batching_files_location=/Users/johnassiamah/elis/softfiles/
app.config.publicaton_files_location=/Users/johnassiamah/elis/documents/publications/
app.config.tempfile_location=/Users/johnassiamah/elis/documents/temp_upload/
app.config.lrd_jacket_raw_path=/Users/johnassiamah/elis/documents/lrd_maps/
app.config.egcr_url=https://cagdmdaapi.paqtechnologies.com/v1/receipts/
app.config.egcr_apikey=nbNe++11+wVPnZmPz+BTSkkxd0hCQsIURKp7cHnpcnw=
app.config.payment_gateway_base_uri=https://www.govgh.org/api/v1.1/
app.config.lc_payment_redirect_url=http://40.71.191.44:8080/onlineservices/payment_confirmation
app.config.lc_payment_post_url=http://41.66.204.146:9293/gelis_online_service_live/rest/payment/confirm_post
app.config.gog_payment_api_key=3a8c4e86f98f65240774626920fe5eb4c9ebfe756cd2433fb0e78c46fa82d2721551226f33c9eab890e1d9f0d8fa8732b85333bcc22c79326f31a6193a6e84798699b402f8e6219d570e87829d5f19091c08bbd2001ff4b4b0c86942f7d5cdc6633cd598a70667aff8c0969aa6dd747d
app.config.email_config_host=mail.aibtrust.irish
app.config.email_config_pass=123!@#Admin
app.config.email_config_user=james@aibtrust.irish
app.config.payment_api_url=https://payment.casantey.com/PaymentUtil/api/
app.config.payment_api_key=TENQb3J0YWw6UEB5bW4zTlRAY2JzZw
